# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:
  - name: CK's Notepad
    url: https://blog.kevinyang.net/
  - name: Ryan | 不務正業 全端 開發記事
    url: http://blog.ryantseng.idv.tw/
  - name: The Will Will Web | Will 保哥
    url: https://blog.miniasp.com/
  - name: 點燈坊
    url: http://oomusou.io/
  - name: 全端開發人員天梯
    url: https://wellwind.idv.tw/blog/
  - name: POY CHANG | Trial and Error
    url: https://poychang.github.io/
  - name: Jeffs WebTech Note
    url: https://jeffwu85182.github.io/
  - name: Duran 的技術冶煉廠
    url: https://dog0416.blogspot.com/
  - name: 程式宅急便
    url: http://kyleap.blogspot.com/
  - name: CSS可樂
    url: http://csscoke.com

# navigation menu
menu:
  - name: Home
    slug: home
    url: /
  - name: Archives
    slug: archives
    url: /archives
  - name: About
    slug: about
    url: /about

# widgets
widgets:
  - about
  - links
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/jiaming0708
- slug: twitter
  url: https://twitter.com/Secret_GoGo
- slug: rss
  url: /atom.xml